/** 非列表银行：自定义名称时使用，主题色用于详情页 */
const BANK_CUSTOM_CODE = 'CUSTOM';

const CUSTOM_BANK_META = {
  code: BANK_CUSTOM_CODE,
  name: '',
  color: '#64748b',
};

const BANKS = [
  { code: 'CMB', name: '招商银行', color: '#C8102E' },
  { code: 'CCB', name: '中国建设银行', color: '#003B8F' },
  { code: 'ICBC', name: '中国工商银行', color: '#C41230' },
  { code: 'ABC', name: '中国农业银行', color: '#319C8B' },
  { code: 'BOC', name: '中国银行', color: '#B61C22' },
  { code: 'BCM', name: '交通银行', color: '#00367A' },
  { code: 'PSBC', name: '中国邮政储蓄银行', color: '#007F3E' },
  { code: 'SPDB', name: '浦发银行', color: '#003B7A' },
  { code: 'CMBC', name: '民生银行', color: '#005BAC' },
  { code: 'CEB', name: '中国光大银行', color: '#691B7E' },
  { code: 'CITIC', name: '中信银行', color: '#E60012' },
  { code: 'PAB', name: '平安银行', color: '#FF6A00' },
  { code: 'GDB', name: '广发银行', color: '#E4002B' },
  { code: 'CIB', name: '兴业银行', color: '#004889' },
  { code: 'HXB', name: '华夏银行', color: '#D80C18' },
  { code: 'ARCU', name: '安徽省农村信用社', color: '#64748b' },
  { code: 'ASCB', name: '鞍山银行', color: '#64748b' },
  { code: 'AYCB', name: '安阳银行', color: '#64748b' },
  { code: 'BANKWF', name: '潍坊银行', color: '#64748b' },
  { code: 'BGB', name: '广西北部湾银行', color: '#64748b' },
  { code: 'BHB', name: '河北银行', color: '#64748b' },
  { code: 'BJBANK', name: '北京银行', color: '#64748b' },
  { code: 'BJRCB', name: '北京农村商业银行', color: '#64748b' },
  { code: 'BOCD', name: '承德银行', color: '#64748b' },
  { code: 'BOCY', name: '朝阳银行', color: '#64748b' },
  { code: 'BOD', name: '东莞银行', color: '#64748b' },
  { code: 'BODD', name: '丹东银行', color: '#64748b' },
  { code: 'BOHAIB', name: '渤海银行', color: '#64748b' },
  { code: 'BOJZ', name: '锦州银行', color: '#64748b' },
  { code: 'BOP', name: '平顶山银行', color: '#64748b' },
  { code: 'BOQH', name: '青海银行', color: '#64748b' },
  { code: 'BOSZ', name: '苏州银行', color: '#64748b' },
  { code: 'BOYK', name: '营口银行', color: '#64748b' },
  { code: 'BOZK', name: '周口银行', color: '#64748b' },
  { code: 'BSB', name: '包商银行', color: '#64748b' },
  { code: 'BZMD', name: '驻马店银行', color: '#64748b' },
  { code: 'CBBQS', name: '城市商业银行资金清算中心', color: '#64748b' },
  { code: 'CBKF', name: '开封市商业银行', color: '#64748b' },
  { code: 'CCQTGB', name: '重庆三峡银行', color: '#64748b' },
  { code: 'CDB', name: '国家开发银行', color: '#64748b' },
  { code: 'CDCB', name: '成都银行', color: '#64748b' },
  { code: 'CDRCB', name: '成都农商银行', color: '#64748b' },
  { code: 'CGNB', name: '南充市商业银行', color: '#64748b' },
  { code: 'COMM', name: '交通银行', color: '#00367A' },
  { code: 'CQBANK', name: '重庆银行', color: '#64748b' },
  { code: 'CRCBANK', name: '重庆农村商业银行', color: '#64748b' },
  { code: 'CSCB', name: '长沙银行', color: '#64748b' },
  { code: 'CSRCB', name: '常熟农村商业银行', color: '#64748b' },
  { code: 'CZBANK', name: '浙商银行', color: '#64748b' },
  { code: 'CZCB', name: '浙江稠州商业银行', color: '#64748b' },
  { code: 'CZRCB', name: '常州农村信用联社', color: '#64748b' },
  { code: 'DAQINGB', name: '龙江银行', color: '#64748b' },
  { code: 'DLB', name: '大连银行', color: '#64748b' },
  { code: 'DRCBCL', name: '东莞农村商业银行', color: '#64748b' },
  { code: 'DYCB', name: '德阳商业银行', color: '#64748b' },
  { code: 'DYCCB', name: '东营市商业银行', color: '#64748b' },
  { code: 'DZBANK', name: '德州银行', color: '#64748b' },
  { code: 'EGBANK', name: '恒丰银行', color: '#64748b' },
  { code: 'FDB', name: '富滇银行', color: '#64748b' },
  { code: 'FJHXBC', name: '福建海峡银行', color: '#64748b' },
  { code: 'FSCB', name: '抚顺银行', color: '#64748b' },
  { code: 'FXCB', name: '阜新银行', color: '#64748b' },
  { code: 'GCB', name: '广州银行', color: '#64748b' },
  { code: 'GDRCC', name: '广东省农村信用社联合社', color: '#64748b' },
  { code: 'GLBANK', name: '桂林银行', color: '#64748b' },
  { code: 'GRCB', name: '广州农商银行', color: '#64748b' },
  { code: 'GSRCU', name: '甘肃省农村信用', color: '#64748b' },
  { code: 'GXRCU', name: '广西省农村信用', color: '#64748b' },
  { code: 'GYCB', name: '贵阳市商业银行', color: '#64748b' },
  { code: 'GZB', name: '赣州银行', color: '#64748b' },
  { code: 'GZRCU', name: '贵州省农村信用社', color: '#64748b' },
  { code: 'H3CB', name: '内蒙古银行', color: '#64748b' },
  { code: 'HANABANK', name: '韩亚银行', color: '#64748b' },
  { code: 'HBC', name: '湖北银行', color: '#64748b' },
  { code: 'HBHSBANK', name: '湖北银行黄石分行', color: '#64748b' },
  { code: 'HBRCU', name: '河北省农村信用社', color: '#64748b' },
  { code: 'HBYCBANK', name: '湖北银行宜昌分行', color: '#64748b' },
  { code: 'HDBANK', name: '邯郸银行', color: '#64748b' },
  { code: 'HKB', name: '汉口银行', color: '#64748b' },
  { code: 'HKBEA', name: '东亚银行', color: '#64748b' },
  { code: 'HNRCC', name: '湖南省农村信用社', color: '#64748b' },
  { code: 'HNRCU', name: '河南省农村信用', color: '#64748b' },
  { code: 'HRXJB', name: '华融湘江银行', color: '#64748b' },
  { code: 'HSBANK', name: '徽商银行', color: '#64748b' },
  { code: 'HSBC', name: '汇丰银行', color: '#64748b' },
  { code: 'HSBK', name: '衡水银行', color: '#64748b' },
  { code: 'HURCB', name: '湖北省农村信用社', color: '#64748b' },
  { code: 'HXBANK', name: '华夏银行', color: '#D80C18' },
  { code: 'HZCB', name: '杭州银行', color: '#64748b' },
  { code: 'HZCCB', name: '湖州市商业银行', color: '#64748b' },
  { code: 'JHBANK', name: '金华银行', color: '#64748b' },
  { code: 'JINCHB', name: '晋城银行', color: '#64748b' },
  { code: 'JJBANK', name: '九江银行', color: '#64748b' },
  { code: 'JLBANK', name: '吉林银行', color: '#64748b' },
  { code: 'JLRCU', name: '吉林农信', color: '#64748b' },
  { code: 'JNBANK', name: '济宁银行', color: '#64748b' },
  { code: 'JRCB', name: '江苏江阴农村商业银行', color: '#64748b' },
  { code: 'JSB', name: '晋商银行', color: '#64748b' },
  { code: 'JSBANK', name: '江苏银行', color: '#64748b' },
  { code: 'JSRCU', name: '江苏省农村信用联合社', color: '#64748b' },
  { code: 'JXBANK', name: '嘉兴银行', color: '#64748b' },
  { code: 'JXRCU', name: '江西省农村信用', color: '#64748b' },
  { code: 'JZBANK', name: '晋中银行', color: '#64748b' },
  { code: 'KLB', name: '昆仑银行', color: '#64748b' },
  { code: 'KORLABANK', name: '库尔勒市商业银行', color: '#64748b' },
  { code: 'KSRB', name: '昆山农村商业银行', color: '#64748b' },
  { code: 'LANGFB', name: '廊坊银行', color: '#64748b' },
  { code: 'LSBANK', name: '莱商银行', color: '#64748b' },
  { code: 'LSBC', name: '临商银行', color: '#64748b' },
  { code: 'LSCCB', name: '乐山市商业银行', color: '#64748b' },
  { code: 'LYBANK', name: '洛阳银行', color: '#64748b' },
  { code: 'LYCB', name: '辽阳市商业银行', color: '#64748b' },
  { code: 'LZYH', name: '兰州银行', color: '#64748b' },
  { code: 'MTBANK', name: '浙江民泰商业银行', color: '#64748b' },
  { code: 'NBBANK', name: '宁波银行', color: '#64748b' },
  { code: 'NBYZ', name: '鄞州银行', color: '#64748b' },
  { code: 'NCB', name: '南昌银行', color: '#64748b' },
  { code: 'NHB', name: '南海农商银行', color: '#64748b' },
  { code: 'NHQS', name: '农信银清算中心', color: '#64748b' },
  { code: 'NJCB', name: '南京银行', color: '#64748b' },
  { code: 'NXBANK', name: '宁夏银行', color: '#64748b' },
  { code: 'NXRCU', name: '宁夏黄河农村商业银行', color: '#64748b' },
  { code: 'NYNB', name: '广东南粤银行', color: '#64748b' },
  { code: 'ORBANK', name: '鄂尔多斯银行', color: '#64748b' },
  { code: 'QDCCB', name: '青岛银行', color: '#64748b' },
  { code: 'QLBANK', name: '齐鲁银行', color: '#64748b' },
  { code: 'SCCB', name: '三门峡银行', color: '#64748b' },
  { code: 'SCRCU', name: '四川省农村信用', color: '#64748b' },
  { code: 'SDEB', name: '顺德农商银行', color: '#64748b' },
  { code: 'SDRCU', name: '山东农信', color: '#64748b' },
  { code: 'SHBANK', name: '上海银行', color: '#64748b' },
  { code: 'SHRCB', name: '上海农村商业银行', color: '#64748b' },
  { code: 'SJBANK', name: '盛京银行', color: '#64748b' },
  { code: 'SMXB', name: '三门峡银行', color: '#64748b' },
  { code: 'SPABANK', name: '平安银行', color: '#FF6A00' },
  { code: 'SRBANK', name: '上饶银行', color: '#64748b' },
  { code: 'SRCB', name: '深圳农村商业银行', color: '#64748b' },
  { code: 'SXCB', name: '绍兴银行', color: '#64748b' },
  { code: 'SXRCCU', name: '陕西信合', color: '#64748b' },
  { code: 'SZSBK', name: '石嘴山银行', color: '#64748b' },
  { code: 'TACCB', name: '泰安市商业银行', color: '#64748b' },
  { code: 'TCCB', name: '天津银行', color: '#64748b' },
  { code: 'TCRCB', name: '江苏太仓农村商业银行', color: '#64748b' },
  { code: 'TRCB', name: '天津农商银行', color: '#64748b' },
  { code: 'TZCB', name: '台州银行', color: '#64748b' },
  { code: 'URMQCCB', name: '乌鲁木齐市商业银行', color: '#64748b' },
  { code: 'WHCCB', name: '威海市商业银行', color: '#64748b' },
  { code: 'WHRCB', name: '武汉农村商业银行', color: '#64748b' },
  { code: 'WJRCB', name: '吴江农商银行', color: '#64748b' },
  { code: 'WRCB', name: '无锡农村商业银行', color: '#64748b' },
  { code: 'WZCB', name: '温州银行', color: '#64748b' },
  { code: 'XABANK', name: '西安银行', color: '#64748b' },
  { code: 'XCYH', name: '中原银行', color: '#64748b' },
  { code: 'XLBANK', name: '中山小榄村镇银行', color: '#64748b' },
  { code: 'XTB', name: '邢台银行', color: '#64748b' },
  { code: 'XXBANK', name: '新乡银行', color: '#64748b' },
  { code: 'XYBANK', name: '信阳银行', color: '#64748b' },
  { code: 'YBCCB', name: '宜宾市商业银行', color: '#64748b' },
  { code: 'YDRCB', name: '尧都农商行', color: '#64748b' },
  { code: 'YNRCC', name: '云南省农村信用社', color: '#64748b' },
  { code: 'YQCCB', name: '阳泉银行', color: '#64748b' },
  { code: 'YXCCB', name: '玉溪市商业银行', color: '#64748b' },
  { code: 'ZBCB', name: '齐商银行', color: '#64748b' },
  { code: 'ZGCCB', name: '自贡市商业银行', color: '#64748b' },
  { code: 'ZJKCCB', name: '张家口市商业银行', color: '#64748b' },
  { code: 'ZJNX', name: '浙江省农村信用社联合社', color: '#64748b' },
  { code: 'ZJTLCB', name: '浙江泰隆商业银行', color: '#64748b' },
  { code: 'ZRCBANK', name: '张家港农村商业银行', color: '#64748b' },
  { code: 'ZYCBANK', name: '遵义市商业银行', color: '#64748b' },
  { code: 'ZZBANK', name: '郑州银行', color: '#64748b' },
];

function byCode(code) {
  if (code === BANK_CUSTOM_CODE) {
    return CUSTOM_BANK_META;
  }
  return BANKS.find((b) => b.code === code) || null;
}

module.exports = { BANKS, BANK_CUSTOM_CODE, byCode };
