/** 非列表银行：自定义名称时使用，主题色用于详情页 */
const BANK_CUSTOM_CODE = 'CUSTOM';

const CUSTOM_BANK_META = {
  code: BANK_CUSTOM_CODE,
  name: '',
  color: '#64748b',
};

const BANKS = [
  { code: 'CMB', name: '招商银行', color: '#C8102E' },
  { code: 'CCB', name: '中国建设银行', color: '#003B8F' },
  { code: 'ICBC', name: '中国工商银行', color: '#C41230' },
  { code: 'ABC', name: '中国农业银行', color: '#319C8B' },
  { code: 'BOC', name: '中国银行', color: '#B61C22' },
  { code: 'BCM', name: '交通银行', color: '#00367A' },
  { code: 'PSBC', name: '中国邮政储蓄银行', color: '#007F3E' },
  { code: 'SPDB', name: '浦发银行', color: '#003B7A' },
  { code: 'CMBC', name: '民生银行', color: '#005BAC' },
  { code: 'CEB', name: '中国光大银行', color: '#691B7E' },
  { code: 'CITIC', name: '中信银行', color: '#E60012' },
  { code: 'PAB', name: '平安银行', color: '#FF6A00' },
  { code: 'GDB', name: '广发银行', color: '#E4002B' },
  { code: 'CIB', name: '兴业银行', color: '#004889' },
  { code: 'HXB', name: '华夏银行', color: '#D80C18' },
  { code: 'ARCU', name: '安徽省农村信用社', color: '#DA261C' },
  { code: 'ASCB', name: '鞍山银行', color: '#B0171C' },
  { code: 'AYCB', name: '安阳银行', color: '#EA4609' },
  { code: 'BANKWF', name: '潍坊银行', color: '#B50E1A' },
  { code: 'BGB', name: '广西北部湾银行', color: '#EC8E10' },
  { code: 'BHB', name: '河北银行', color: '#093784' },
  { code: 'BJBANK', name: '北京银行', color: '#C9131B' },
  { code: 'BJRCB', name: '北京农村商业银行', color: '#C9131B' },
  { code: 'BOCD', name: '承德银行', color: '#B8001A' },
  { code: 'BOCY', name: '朝阳银行', color: '#005BAC' },
  { code: 'BOD', name: '东莞银行', color: '#D40C12' },
  { code: 'BODD', name: '丹东银行', color: '#29166F' },
  { code: 'BOHAIB', name: '渤海银行', color: '#29166F' },
  { code: 'BOJZ', name: '锦州银行', color: '#E70113' },
  { code: 'BOP', name: '平顶山银行', color: '#B8191D' },
  { code: 'BOQH', name: '青海银行', color: '#69D405' },
  { code: 'BOSZ', name: '苏州银行', color: '#69D405' },
  { code: 'BOYK', name: '营口银行', color: '#03438C' },
  { code: 'BOZK', name: '周口银行', color: '#DD0202' },
  { code: 'BSB', name: '包商银行', color: '#4A190F' },
  { code: 'BZMD', name: '驻马店银行', color: '#058CD5' },
  { code: 'CBBQS', name: '城市商业银行资金清算中心', color: '#FE435A' },
  { code: 'CBKF', name: '开封市商业银行', color: '#64748b' },
  { code: 'CCQTGB', name: '重庆三峡银行', color: '#64748b' },
  { code: 'CDB', name: '国家开发银行', color: '#E50210' },
  { code: 'CDCB', name: '成都银行', color: '#F19603' },
  { code: 'CDRCB', name: '成都农商银行', color: '#03663B' },
  { code: 'CGNB', name: '南充市商业银行', color: '#64748b' },
  { code: 'COMM', name: '交通银行', color: '#00367A' },
  { code: 'CQBANK', name: '重庆银行', color: '#02AB4D' },
  { code: 'CRCBANK', name: '重庆农村商业银行', color: '#FD0101' },
  { code: 'CSCB', name: '长沙银行', color: '#D9231C' },
  { code: 'CSRCB', name: '常熟农村商业银行', color: '#971D43' },
  { code: 'CZBANK', name: '浙商银行', color: '#DEB618' },
  { code: 'CZCB', name: '浙江稠州商业银行', color: '#A92226' },
  { code: 'CZRCB', name: '常州农村信用联社', color: '#AD0B2A' },
  { code: 'DAQINGB', name: '龙江银行', color: '#FABE01' },
  { code: 'DLB', name: '大连银行', color: '#D41518' },
  { code: 'DRCBCL', name: '东莞农村商业银行', color: '#CF0101' },
  { code: 'DYCB', name: '德阳商业银行', color: '#D30B23' },
  { code: 'DYCCB', name: '东营市商业银行', color: '#C9252C' },
  { code: 'DZBANK', name: '德州银行', color: '#C9252C' },
  { code: 'EGBANK', name: '恒丰银行', color: '#003D7E' },
  { code: 'FDB', name: '富滇银行', color: '#9D2330' },
  { code: 'FJHXBC', name: '福建海峡银行', color: '#025197' },
  { code: 'FSCB', name: '抚顺银行', color: '#CE030B' },
  { code: 'FXCB', name: '阜新银行', color: '#0053A5' },
  { code: 'GCB', name: '广州银行', color: '#DA231B' },
  { code: 'GDRCC', name: '广东省农村信用社联合社', color: '#447734' },
  { code: 'GLBANK', name: '桂林银行', color: '#257CBB' },
  { code: 'GRCB', name: '广州农商银行', color: '#64748b' },
  { code: 'GSRCU', name: '甘肃省农村信用', color: '#067737' },
  { code: 'GXRCU', name: '广西省农村信用', color: '#01441A' },
  { code: 'GYCB', name: '贵阳市商业银行', color: '#E60113' },
  { code: 'GZB', name: '赣州银行', color: '#E70113' },
  { code: 'GZRCU', name: '贵州省农村信用社', color: '#06A745' },
  { code: 'H3CB', name: '内蒙古银行', color: '#CF020E' },
  { code: 'HANABANK', name: '韩亚银行', color: '#0A9475' },
  { code: 'HBC', name: '湖北银行', color: '#D32846' },
  { code: 'HBHSBANK', name: '湖北银行黄石分行', color: '#D32846' },
  { code: 'HBRCU', name: '河北省农村信用社', color: '#447734' },
  { code: 'HBYCBANK', name: '湖北银行宜昌分行', color: '#D32846' },
  { code: 'HDBANK', name: '邯郸银行', color: '#00499E' },
  { code: 'HKB', name: '汉口银行', color: '#0286B3' },
  { code: 'HKBEA', name: '东亚银行', color: '#E8150D' },
  { code: 'HNRCC', name: '湖南省农村信用社', color: '#E70204' },
  { code: 'HNRCU', name: '河南省农村信用', color: '#B60202' },
  { code: 'HRXJB', name: '华融湘江银行', color: '#C8020B' },
  { code: 'HSBANK', name: '徽商银行', color: '#C4251C' },
  { code: 'HSBC', name: '汇丰银行', color: '#ED292C' },
  { code: 'HSBK', name: '衡水银行', color: '#044693' },
  { code: 'HURCB', name: '湖北省农村信用社', color: '#0329CE' },
  { code: 'HXBANK', name: '华夏银行', color: '#D80C18' },
  { code: 'HZCB', name: '杭州银行', color: '#36ADF8' },
  { code: 'HZCCB', name: '湖州市商业银行', color: '#DB9610' },
  { code: 'JHBANK', name: '金华银行', color: '#E67715' },
  { code: 'JINCHB', name: '晋城银行', color: '#C8142C' },
  { code: 'JJBANK', name: '九江银行', color: '#CE010C' },
  { code: 'JLBANK', name: '吉林银行', color: '#DC0817' },
  { code: 'JLRCU', name: '吉林农信', color: '#F08E03' },
  { code: 'JNBANK', name: '济宁银行', color: '#F39705' },
  { code: 'JRCB', name: '江苏江阴农村商业银行', color: '#028337' },
  { code: 'JSB', name: '晋商银行', color: '#ED1B23' },
  { code: 'JSBANK', name: '江苏银行', color: '#0165B3' },
  { code: 'JSRCU', name: '江苏省农村信用联合社', color: '#F39301' },
  { code: 'JXBANK', name: '嘉兴银行', color: '#0375C2' },
  { code: 'JXRCU', name: '江西省农村信用', color: '#447734' },
  { code: 'JZBANK', name: '晋中银行', color: '#A72328' },
  { code: 'KLB', name: '昆仑银行', color: '#C3141B' },
  { code: 'KORLABANK', name: '库尔勒市商业银行', color: '#C80D12' },
  { code: 'KSRB', name: '昆山农村商业银行', color: '#AC2419' },
  { code: 'LANGFB', name: '廊坊银行', color: '#0668B4' },
  { code: 'LSBANK', name: '莱商银行', color: '#CE010C' },
  { code: 'LSBC', name: '临商银行', color: '#C8261E' },
  { code: 'LSCCB', name: '乐山市商业银行', color: '#E40111' },
  { code: 'LYBANK', name: '洛阳银行', color: '#022BAA' },
  { code: 'LYCB', name: '辽阳市商业银行', color: '#C7010C' },
  { code: 'LZYH', name: '兰州银行', color: '#1F3081' },
  { code: 'MTBANK', name: '浙江民泰商业银行', color: '#F31126' },
  { code: 'NBBANK', name: '宁波银行', color: '#EA731A' },
  { code: 'NBYZ', name: '鄞州银行', color: '#0A994F' },
  { code: 'NCB', name: '南昌银行', color: '#059492' },
  { code: 'NHB', name: '南海农商银行', color: '#B32D50' },
  { code: 'NHQS', name: '农信银清算中心', color: '#447734' },
  { code: 'NJCB', name: '南京银行', color: '#E60211' },
  { code: 'NXBANK', name: '宁夏银行', color: '#E70011' },
  { code: 'NXRCU', name: '宁夏黄河农村商业银行', color: '#E50217' },
  { code: 'NYNB', name: '广东南粤银行', color: '#970303' },
  { code: 'ORBANK', name: '鄂尔多斯银行', color: '#D40A05' },
  { code: 'QDCCB', name: '青岛银行', color: '#E60202' },
  { code: 'QLBANK', name: '齐鲁银行', color: '#F6A010' },
  { code: 'SCCB', name: '三门峡银行', color: '#3974AF' },
  { code: 'SCRCU', name: '四川省农村信用', color: '#01792F' },
  { code: 'SDEB', name: '顺德农商银行', color: '#02158A' },
  { code: 'SDRCU', name: '山东农信', color: '#EB1C24' },
  { code: 'SHBANK', name: '上海银行', color: '#0110AB' },
  { code: 'SHRCB', name: '上海农村商业银行', color: '#0D2481' },
  { code: 'SJBANK', name: '盛京银行', color: '#E6141B' },
  { code: 'SMXB', name: '三门峡银行', color: '#3974AF' },
  { code: 'SPABANK', name: '平安银行', color: '#FF6A00' },
  { code: 'SRBANK', name: '上饶银行', color: '#FE9901' },
  { code: 'SRCB', name: '深圳农村商业银行', color: '#026AB0' },
  { code: 'SXCB', name: '绍兴银行', color: '#F6EE04' },
  { code: 'SXRCCU', name: '陕西信合', color: '#023515' },
  { code: 'SZSBK', name: '石嘴山银行', color: '#5B3C0C' },
  { code: 'TACCB', name: '泰安市商业银行', color: '#033398' },
  { code: 'TCCB', name: '天津银行', color: '#00499F' },
  { code: 'TCRCB', name: '江苏太仓农村商业银行', color: '#314D78' },
  { code: 'TRCB', name: '天津农商银行', color: '#EC5605' },
  { code: 'TZCB', name: '台州银行', color: '#55C2D5' },
  { code: 'URMQCCB', name: '乌鲁木齐市商业银行', color: '#015AAA' },
  { code: 'WHCCB', name: '威海市商业银行', color: '#0268B6' },
  { code: 'WHRCB', name: '武汉农村商业银行', color: '#D82519' },
  { code: 'WJRCB', name: '吴江农商银行', color: '#FE0101' },
  { code: 'WRCB', name: '无锡农村商业银行', color: '#FE0202' },
  { code: 'WZCB', name: '温州银行', color: '#F6AD2C' },
  { code: 'XABANK', name: '西安银行', color: '#002859' },
  { code: 'XCYH', name: '中原银行', color: '#058CD5' },
  { code: 'XLBANK', name: '中山小榄村镇银行', color: '#D9251B' },
  { code: 'XTB', name: '邢台银行', color: '#6BAF30' },
  { code: 'XXBANK', name: '新乡银行', color: '#C90817' },
  { code: 'XYBANK', name: '信阳银行', color: '#D8251C' },
  { code: 'YBCCB', name: '宜宾市商业银行', color: '#1D2088' },
  { code: 'YDRCB', name: '尧都农商行', color: '#019A44' },
  { code: 'YNRCC', name: '云南省农村信用社', color: '#FD0200' },
  { code: 'YQCCB', name: '阳泉银行', color: '#CA2328' },
  { code: 'YXCCB', name: '玉溪市商业银行', color: '#D9251B' },
  { code: 'ZBCB', name: '齐商银行', color: '#CB060D' },
  { code: 'ZGCCB', name: '自贡市商业银行', color: '#FC0607' },
  { code: 'ZJKCCB', name: '张家口市商业银行', color: '#E60112' },
  { code: 'ZJNX', name: '浙江省农村信用社联合社', color: '#039945' },
  { code: 'ZJTLCB', name: '浙江泰隆商业银行', color: '#E15A1E' },
  { code: 'ZRCBANK', name: '张家港农村商业银行', color: '#031BCE' },
  { code: 'ZYCBANK', name: '遵义市商业银行', color: '#E80111' },
  { code: 'ZZBANK', name: '郑州银行', color: '#DB2B1C' },
];

function byCode(code) {
  if (code === BANK_CUSTOM_CODE) {
    return CUSTOM_BANK_META;
  }
  return BANKS.find((b) => b.code === code) || null;
}

module.exports = { BANKS, BANK_CUSTOM_CODE, byCode };
